### PR TITLE
Dynamic Dashboard

### PR DESCRIPTION
**Pull request by incraigulous**
Adds dynamic add/remove/sort/register functionality to the dashboard. 

https://www.loom.com/share/b81353f166be4f8c99f0b6228710497b

See the readme for instructions for registering custom cards. 

**Future plans:** 
- We would like to investigate integrating GridStack to add resize/drag/drop functionality. 
- Add more cards!!!

### CODE REVIEW

**Comment by incraigulous** [comment]
@corsacca

**Comment by corsacca** [comment]
Thanks @incraigulous !
Initial overview thoughts:

1. Little bit weird behavior or med size screen.

image

2. Trying to hide the cards i get:

image

3. thoughts on fullscreen (using all the width)?

4. Weird admin sorting bug. If i bring tasks to the top and refresh, the whole order gets reset.
tasks


Subjective:
5. The grey background makes the tiles stand out better. But maybe that is not what we are going for

image

**Comment by incraigulous** [comment]
@corsacca, can you check to see if the sort function still 404s for you? I'm not quite sure what is causing it, but I'm wondering if your failing the rest route `permission_callback`. I made an adjustment to that logic. Can you also confirm that your user has the `access_contacts` capability?

**Comment by incraigulous** [comment]
@corsacca, I'm not sure if you noticed, but I made style fixes last week.

**Comment by corsacca** [comment]
> @corsacca, can you check to see if the sort function still 404s for you? I'm not quite sure what is causing it, but I'm wondering if your failing the rest route `permission_callback`.

image
My instance url is `http://multisite.local/enabled/`

**Comment by corsacca** [comment]
FYI:
image

**Comment by incraigulous** [comment]
@corsacca, I've fixed the console errors.

**Comment by corsacca** [comment]
@incraigulous Awesome!!!

**Comment by corsacca** [comment]
Let's give this a whirl!

**Pull request merged**
